### ISSUE TITLE
duplicate `containerPort` with distinct `protocol` are not rendered correctly

### ISSUE THREAD

**Issue by herwigstuetz** [hall/kubenix#13]
Exposing the same `containerPort` on both `TCP` and `UDP` does not work as only one port ends up in the manifest, see the example below.

After some digging, I found out that the `x-kubernetes-patch-merge-key` for `ports` in `io.k8s.api.core.v1.Container` in the [swagger spec](https://raw.githubusercontent.com/kubernetes/kubernetes/v1.26.0/api/openapi-spec/swagger.json) consists of only `containerPort` but not `protocol`. And since this is used by [the generator](https://github.com/hall/kubenix/blob/6dfa8e81c72fced722b7182350d82a51128ff059/jobs/generators/k8s/default.nix#L160-L168) to create the module, such ports get dropped during the [evaluation in the module](https://github.com/hall/kubenix/blob/6dfa8e81c72fced722b7182350d82a51128ff059/modules/k8s.nix#L490-L496).

Since this is a [known issue](https://github.com/kubernetes/kubernetes/issues/105610) in kubernetes, kubenix probably shouldn't use `x-kubernetes-patch-strategy` for `ports` to generate the k8s manifests.

# Example

`nix build . ` on the flake
```nix
{
  inputs.kubenix.url = "github:hall/kubenix";

  outputs = {self, kubenix, ... }@inputs: let
    system = "aarch64-linux";
  in {
    packages.${system}.default = (kubenix.evalModules.${system} {
      module = { kubenix, ... }: {
        imports = with kubenix.modules; [k8s];
        kubernetes.resources.deployments.test.spec = {
          selector = {};
          template.spec.containers.test = {
            ports = [
              { containerPort = 53;
                protocol = "TCP";
              }
              { containerPort = 53;
                protocol = "UDP";
              }
            ];
          };
        };
      };
    }).config.kubernetes.resultYAML;
  };
}
```
only produces
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubenix/k8s-version: '1.26'
    kubenix/project-name: kubenix
  name: test
spec:
  selector: {}
  template:
    spec:
      containers:
      - name: test
        ports:
        - containerPort: 53
          protocol: TCP
```
and is missing
```yaml
        - containerPort: 53
          protocol: UDP
```

**Comment by herwigstuetz** [comment]
@hall, thanks for looking into this, but also thanks for driving kubenix forward!

I think the merge strategy described in https://kubernetes.io/docs/reference/using-api/server-side-apply/#merge-strategy might be worth looking into, but I'm not sure how easily this can be adopted for the kubenix modules.

For now, as a workaround, I'm basically just excluding `io.k8s.api.core.v1.ContainerPort` from using `x-kubernetes-patch-merge-key`.

**Comment by matejc** [comment]
How about this for a workaround?
In Kubenix:
```nix
              ports = {
                http = { containerPort = 8080; protocol = "TCP"; };
                not-http = { containerPort = 8080; protocol = "UDP"; };
              };
```

It outputs this Yaml:
```yaml
ports:
  - containerPort: 8080
    protocol: TCP
  - containerPort: 8080
    protocol: UDP
```
