### ISSUE TITLE
the order of `initContainers` is not preserved

### ISSUE THREAD

**Issue by herwigstuetz** [hall/kubenix#19]
The `initContainers` of a `Deployment` are sorted by `name`, instead of the order they appear in. This affects e.g. the [Gitea Helm Chart](https://gitea.com/gitea/helm-chart/) where the order of the init containers is relevant.

# Example

The `kubenix` configuration
```nix
{
  inputs.kubenix.url = "github:hall/kubenix";

  outputs = {self, kubenix, ... }@inputs: let
    system = "aarch64-linux";
  in {
    packages.${system}.default = (kubenix.evalModules.${system} {
      module = { kubenix, ... }: {
        imports = with kubenix.modules; [k8s];
        kubernetes.resources.deployments.test.spec = {
          selector = {};
          template.spec = {
            initContainers = [
              { name = "c"; }
              { name = "b"; }
              { name = "a"; }
            ];

            containers = [{ name = "test"; }];
          };
        };
      };
    }).config.kubernetes.resultYAML;
  };
}
```

produces

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubenix/k8s-version: '1.26'
    kubenix/project-name: kubenix
  name: test
spec:
  selector: {}
  template:
    spec:
      containers:
      - name: test
      initContainers:
      - name: a
      - name: b
      - name: c
```

Note that the order of the `initContainers` in the generated `yaml` is `a`, `b`, `c`, whereas it is `c`, `b`, `a` in the nix definition.
