### ISSUE TITLE
Kubenix-managed namespaces

### ISSUE THREAD

**Issue by pizzapim** [hall/kubenix#56]
I would like to have Kubenix create namespaces, which I intent to make Kubenix deploy its resources in using `kubernetes.namespace`. However, if I do this, I get: `Error from server (NotFound): namespaces "kubenix" not found`. A workaround I can think of is deploying the namespaces manually with kubectl, and then using Kubenix for the rest. Is there perhaps a better way?

**Comment by adrian-gierakowski** [comment]
Could you share a code example and the command you ran?

**Comment by pizzapim** [comment]
Here is a code example (imported as a module):
```nix
{
  kubernetes.resources.namespaces.test-namespace = { };
  kubernetes.resources.pods.example = {
    metadata.namespace = "test-namespace";
    spec.containers.nginx.image = "nginx";
  };
}
```

Running this gives the error (:
```shell
$ nix run .#kubenix.x86_64-linux
Error from server (NotFound): namespaces "test-namespace" not found
```

Doing something like this in YAML does work though:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test-namespace
spec:
  containers:
  - name: nginx
    image: nginx
```

```shell
$ kubectl apply -f ./repro.yaml 
namespace/test-namespace created
pod/nginx created
```

Maybe this is caused by the `diff`s?
